/*
    SQL summary:

    This is, with the help of Supabase AI and Gemini, the closest sql query we could come up with to mimic the current setup I have.

    There isn't any row data yet, but my sample database will be able to show you how this works. Row data is tied to auth.users, so
    you can't create users on another database without properly logging in and creating users on the that db. 

    It's enough to say that this should be BAREBONES and should show the intended feature of the test project, which is to set RLS 
    policies that allow viewers to only see their data, and admins to see everything.

    -DC
*/

-- 1) Create tables (best-effort from current metadata)
create table if not exists public.roles (
    id bigint generated by default as identity primary key,
    user_id uuid not null unique default auth.uid(),
    admin boolean
);

create table if not exists public.tasks (
    id bigint generated by default as identity primary key,
    title text,
    assigned_to uuid unique,
    status text
);

-- 2) Enable RLS on both tables
alter table public.roles enable row level security;
alter table public.tasks enable row level security;

-- 3) Policies

-- Checks the roles table if the current user is an admin. If they are, this policy allows them to query anything.
create policy "Admins can do everything"
on public.tasks
for all
to authenticated
using (
  exists (
    select 1
    from public.roles
    where public.roles.user_id = auth.uid()
      and public.roles.admin = true
  )
);

-- If the user isn't an admin, this policy triggers (since the policies are permissive, meaning OR logic applies) and
-- allows the viewer to only see the tasks that match their user id.
create policy "Viewers can read tasks"
on public.tasks
for select
to authenticated
using (assigned_to = auth.uid());

-- This is where I nearly chewed my arm off trying to figure out. This policy allows users to READ THEIR ROLE on the roles table.
-- Important, because they can't see IF THEY ARE AN ADMIN OR NOT without this, and the admin policy just returns false and immediately
-- defaults to the viewer policy instead.
create policy "Users can read own role"
on public.roles
for select
to authenticated
using (user_id = auth.uid());